config/routes.rb
Rails.application.routes.draw do
  get "/", to: "sessions#new"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
  get "/home", to: "home#index"
  get "/yourorder", to: "orders#your_orders"
  post "viewcart", to: "orders#view"
  get "/clerks", to: "clerks#index"
  get "/new_clerk", to: "clerks#new"
  get "/sales_report", to: "orders#report"
  resources :users
  resources :orders
  resources :order_items
  resources :menus
  resources :menu_items
  resources :carts
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :menu_name, presence: true
  has_many :menu_items
  has_many :carts

  def self.active
    if Menu.find_by(active: true)
      Menu.find_by(active: true).id
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]
  before_action :ensure_owner

  def index
    @menus = Menu.all
  end

  def show
  end

  def new
    @menu = Menu.new
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.active
      Menu.update_all(active: false)
    end
    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: "Menu was successfully created." }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    Menu.update_all(active: false)
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: "Menu was successfully updated." }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: "Menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def menu_params
    params.require(:menu).permit(:menu_name, :active)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div class="MenuForm-errorExplanation">
      <h2 class="MenuForm-errorMessage"><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <section class="MenuForm">
    <div class="MenuForm-field">
      <%= form.label :menu_name, class: "MenuForm-label" %>
      <%= form.text_field :menu_name, class: "MenuForm-input1" %>
    </div>

    <div class="MenuForm-field">
      <p class="MenuForm-label">Would you like this menu to be active?</p>
      <%= form.check_box :active, class: "MenuForm-input2" %>
    </div>
    <%= form.submit "I'm done", class: "MenuForm-submitButton" %>
  </section>
<% end %>

app/views/menus/edit.html.erb
<section class="EditMenuPage">
  <h1 class="EditMenuPage-title">Edit Menu</h1>

  <%= render "form", menu: @menu %>

  <p class="MenuPage-link"><%= link_to "Show", @menu %> | <%= link_to "Back", menus_path %></p>
</section>

app/views/menus/index.html.erb
<section class="MenuPage">
  <p id="MenuPage-notice"><%= params[:notice] %></p>

  <h1 class="MenuPage-title">Menus</h1>
  <p style="margin-bottom: 50px"><%= link_to "+ Add Menu", new_menu_path, class: "MenuPage-addMenuLink" %></p>

  <table class="MenuTable">
    <tbody>
      <% @menus.each do |menu| %>
        <tr style="text-align: center">
          <td class="Menu-name"><%= menu.menu_name %></td>
          <td>
            <% if menu.active %>
              <p class="Menu-active">ACTIVE</p>
            <% else %>
              <p class="Menu-notActive">NOT ACTIVE</p>
            <% end %>
          </td>
          <td> <p class="Menu-options"> [<%= link_to "Show", menu %>]</p> </td>
          <td> <p class="Menu-options"> [<%= link_to "Edit", edit_menu_path(menu) %>]</p> </td>
          <td> <p class="Menu-options">
            [<%= link_to "Remove", menu, method: :delete, data: { confirm: "Are you sure?" } %>]
          </p> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/menus/new.html.erb
<section class="NewMenuPage">
  <h1 class="NewMenuPage-title">New Menu</h1>
  <%= render "form", menu: @menu %>
  <p class="MenuPage-link"><%= link_to "Back", menus_path %></p>
</section>

app/views/menus/show.html.erb
<section class="ShowMenuPage">
  <p class="ShowMenuPage-notice"><%= notice %></p>

  <div class="ShowMenu">
    <p class="ShowMenuPage-menuName">
      <strong>Menu name:</strong>
      <%= @menu.menu_name %>
    </p>

    <% if @menu.active %>
      <p class="ShowMenuPage-menuActive">Menu is active for use.</p>
    <% else %>
      <p class="ShowMenuPage-menuActive">Menu is not active now.</p>
      <p class="ShowMenuPage-menuActive">Please try again later!</p>
    <% end %>
  </div>

  <p class="MenuPage-link">
    <%= link_to "Edit", edit_menu_path(@menu) %> | <%= link_to "Back", menus_path %>
  </p>

</section>