config/routes.rb
Rails.application.routes.draw do
  get "/", to: "sessions#new"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
  get "/home", to: "home#index"
  get "/yourorder", to: "orders#your_orders"
  post "viewcart", to: "orders#view"
  get "/clerks", to: "clerks#index"
  get "/new_clerk", to: "clerks#new"
  get "/sales_report", to: "orders#report"
  resources :users
  resources :orders
  resources :order_items
  resources :menus
  resources :menu_items
  resources :carts
end

app/controllers/clerks_controller.rb
class ClerksController < ApplicationController
  before_action :ensure_owner

  def new
  end

  def index
    @users = User.where(role: "clerk")
  end
end

app/views/clerks/index.html.erb
<section class="Clerks">
    <h4 class="Clerks-notice"><%= params[:notice] %></h4>

    <h1 class="Clerks-title">List of all clerks and their email IDs</h1>
    <p class="Clerks-addClerkLink"><%= link_to "Add clerk", new_clerk_path %></p>

    <table class="Clerks-table">
        <tbody>
            <% @users.each do |user| %>
                <tr style="text-align: center">
                    <td class="Clerks-value1"> <%= user.first_name + " " + user.last_name %> </td>
                    <td class="Clerks-value2"> <%= user.email %> </td>
                    <td>
                        <p class="Clerks-link">
                            [ <%= link_to "Remove", user, method: :delete, data: { confirm: "Are you sure?" } %> ]</p>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</section>

app/views/clerks/new.html.erb
<section class="AddClerk">
    <h1 class="AddClerk-title"> Add New Clerk </h1>

    <section class="ClerkForm">
        <%= form_with url: users_path do |form| %>
            <div class="ClerkForm-field">
                <p class="ClerkForm-label">First Name</p>
                <%= form.text_field :first_name, class: "ClerkForm-input1" %>
            </div>
            <div class="ClerkForm-field">
                <p class="ClerkForm-label">Last Name</p>
                <%= form.text_field :last_name, class: "ClerkForm-input2" %>
            </div>
            <div class="ClerkForm-field">
                <p class="ClerkForm-label">Email</p>
                <%= form.email_field :email, class: "ClerkForm-input3" %>
            </div>
            <div class="ClerkForm-field">
                <p class="ClerkForm-label">Password</p>
                <%= form.password_field :password, class: "ClerkForm-input4" %>
            </div>
            <%= form.submit "Add clerk", class: "ClerkForm-submitButton" %>
            <%= hidden_field_tag "role", "clerk" %>
        <% end %>
    </section>
<section>