config/routes.rb
Rails.application.routes.draw do
  get "/", to: "sessions#new"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
  get "/home", to: "home#index"
  get "/yourorder", to: "orders#your_orders"
  post "viewcart", to: "orders#view"
  get "/clerks", to: "clerks#index"
  get "/new_clerk", to: "clerks#new"
  get "/sales_report", to: "orders#report"
  resources :users
  resources :orders
  resources :order_items
  resources :menus
  resources :menu_items
  resources :carts
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  def self.pending_order
    all.where(delivered_at: nil)
  end

  def self.get_report(from, to, user)
    if user != ""
      if user.to_i != 0
        return Order.where("date > ? and date < ? and user_id = ? ", from, to, user)
      else
        if (User.find_by(first_name: user))
          user = User.where(first_name: user).map { |user| user.id }
        else
          user = 0
        end
        return Order.where("date > ? and date < ? and user_id in (?) ", from, to, user)
      end
    end
    Order.where("date > ? and date < ? ", from, to)
  end

  def self.get_details(order_id)
    user_data = {}
    user_data["name"] = Order.find(order_id).user.first_name
    user_data["date"] = Order.find(order_id).date.to_date
    user_data["email"] = Order.find(order_id).user.email
    user_data
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :ensure_owner_or_clerk, only: [:index, :update, :edit]
  before_action :ensure_owner, only: [:report]

  def index
    @orders = Order.pending_order.order(date: :desc)
    @your_order = false
  end

  def your_orders
    @orders = @current_user.orders.order(date: :desc)
    @your_order = true
    render "index"
  end

  def report
    if (params[:to_date])
      @orders = []
      if (params[:to_date] == "" or params[:from_date] == "")
        flash[:error] = "Date can't be empty"
        redirect_to sales_report_path
      elsif (params[:from_date] > params[:to_date])
        flash[:error] = "Invalid Date range"
        redirect_to sales_report_path
      else
        @from_date = params[:from_date].split("-").join("/")
        @from_date = Date.strptime(@from_date, "%Y/%m/%d")
        @to_date = params[:to_date].split("-").join("/")
        @to_date = Date.strptime(@to_date, "%Y/%m/%d")
        @orders = Order.get_report(params[:from_date], params[:to_date], params[:user_id])
        @totals = OrderItem.group(:order_id).sum(:total)
        @count = @orders.count
        @sum = @orders.map { |item| item.order_items.sum(:total) }.sum
      end
    else
      @orders = Order.all
      @totals = OrderItem.group(:order_id).sum(:total)
      @count = Order.count
      @sum = OrderItem.sum(:total)
    end
  end

  def new
    if Menu.active
      current_menu_id = Menu.active
    end
    @menu_items = MenuItem.current_menu(current_menu_id)
  end

  def edit
    @status = @order.status == "preparing"
  end

  def view
    redirect_to carts_path
  end

  def create
    items = @current_user.carts
    if items.count > 0
      new_order = Order.create!(
        user_id: @current_user.id,
        date: Time.now.getutc,
        delivered_at: nil,
        status: "confirm",
      )
    end

    items.each do |item|
      OrderItem.create!(
        order_id: new_order.id,
        menu_item_id: item.menu_item.id,
        menu_item_name: item.menu_item.menu_item_name,
        menu_item_price: item.menu_item.menu_item_price,
        quantity: item.quantity,
        total: item.quantity * item.menu_item.menu_item_price,
      )
    end
    if items.count > 0
      items.destroy_all
      redirect_to yourorder_path(notice: "Order Successfully placed")
    else
      flash[:error] = "Your Cart is empyt !!"
      redirect_to carts_path
    end
  end

  def update
    @order.update(status: params[:status])
    @order.save

    if params[:status] == "delivered"
      @order.update(delivered_at: Time.now.utc)
      @order.save
    end

    redirect_to orders_path(notice: "Order Status Updated Successfully ")
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:user_id, :date, :delivered_at, :status)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_display_menu.html.erb
<section class="DisplayMenu">
    <table class="DisplayMenu-table">
        <% @menu_items.each do |menu_item| %>
            <tr class="DisplayMenu-details">
                <td class="DisplayMenu-itemName"> <%= menu_item.menu_item_name %> </p>
                <td class="DisplayMenu-itemPrice">₹ <%= menu_item.menu_item_price %> </p>
                <td>
                    <%= form_with url: carts_path do |form| %>
                                    <%= hidden_field_tag "menu_item_id", menu_item.id %>
                                    <%= hidden_field_tag "menu_id", menu_item.menu_id %>
                                    <%= hidden_field_tag "user_id", @current_user.id %>
                                    <%= number_field_tag "quantity", 0,
                                                         min: 0, class: "Order-quantity",
                                                         :onclick => "submit()" %>

                    <% end %>
                </td>
            </tr>
        <% end %>
    </table>
</section>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
    <section class="OrderForm">
    <h4 class="OrderForm-title"> Status <h4>
    <div class="Order-div">
        <div class="Order-radio">
            <%= radio_button_tag "status", "confirm", !(@status) %>
            <p class="Options"> Confirmed </p>
        </div>
        <div class="Order-radio">
            <%= radio_button_tag "status", "preparing", @status %>
            <p class="Options"> On your way </p>
        </div>
        <div class="Order-radio">
            <%= radio_button_tag "status", "delivered" %>
            <p class="Options"> Delivered </p>
        </div>
    </div>
    <%= submit_tag "Update Order", class: "Order-submitButton" %>
</section>
<% end %>

app/views/orders/edit.html.erb
<section class="EditOrder">
  <h1 class="NewOrderPage-title">Editing Order</h1>

  <%= render "form", order: @order %>

  <p class="EditOrder-link">
    <%= link_to "Show", @order %> | <%= link_to "Back", orders_path %>
  </p>
</section>

app/views/orders/index.html.erb
<section class="YourOrders">
  <h4 class="YourOrders-notice"> <%= params[:notice] %> </h4>
  <% order_title = "Pending Orders" %>
  <% order_title = "Your Orders" if @your_order %>
  <h1 class="YourOrders-title"> <%= order_title %> </h1>

  <p class="YourOrders-link"> <%= link_to "New Order", new_order_path %> <p>

  <table class="YourOrders-table">
    <tr class="YourTable-tableHeader">
      <% if not @your_order %> <th class="YourTable-headerValue">Order Id</th> <% end %>
      <% if not @your_order %> <th class="YourTable-headerValue">User</th> <% end %>
      <th class="YourTable-headerValue">Date</th>
      <th class="YourTable-headerValue">Delivered at</th>
      <th class="YourTable-headerValue">Status</th>
      <th colspan="2"></th>
    </tr>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <% if not @your_order %>
            <td class="YourTable-value"> <%= order.id %> </td>
          <% end %>
          <% if not @your_order %>
            <td> <p class="YourTable-value"><%= order.user.first_name %></p> </td>
          <% end %>
          <td class="YourTable-value"> <%= order.date %> </td>
          <td class="YourTable-value">
            <% if order.delivered_at == nil %>
              <p class="YourTable-value">--NIL--</p>
            <% else %>
              <%= order.delivered_at %>
            <% end %>
          </td>
          <td class="YourTable-value"> <%= order.status %> </td>
          <td class="YourTable-value"> <%= link_to "Show", order_items_path(order_id: order.id) %> </td>
          <% if (not(@current_user.is_customer(@current_user.id))) and not @your_order %>
            <td class="YourTable-value"> <%= link_to "Edit", edit_order_path(order) %> </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

</section>

app/views/orders/new.html.erb
<section class="NewOrderPage">
    <h1 class="NewOrderPage-title">New Order</h1>
    <p class="NewOrderPage-message">Orders taken for the menu currently active now</p>

    <%= render partial: "display_menu",
               locals: {
                 menu_items: @menu_items,
               } %>

    <div>
        <%= form_with url: viewcart_path do |form| %>
        <div>
            <%= submit_tag "View cart", class: "NewOrderPage-submitButton" %>
        </div>
        <% end %>
    </div>
</section>

app/views/orders/report.html.erb
<section class="Report">
  <p class="Report-notice"> <%= params[:notice] %> </p>

  <h1 class="Report-title">Sales report</h1>

  <%= form_with url: sales_report_path, method: "GET", local: true do |form| %>
    <section class="Report-form">
      <div class="Report-duration">
        <p class="Report-label"> From </p>
        <%= date_field_tag "from_date", @from_date %>
        <p class="Report-label"> To </p>
        <%= date_field_tag "to_date", @to_date %>
      </div>
      <%= text_field_tag "user_id", nil, value: params[:user_id],
                                         placeholder: "User ID/name (optional)" %>

      <%= submit_tag "Generate report", class: "Report-submitButton" %>
    </section>
  <% end %>

  <table class="Report-table">
    <thead>
      <tr class="Report-tableHeader">
        <th class="Report-headerValue">User</th>
        <th class="Report-headerValue">Date</th>
        <th class="Report-headerValue">Delivered at</th>
        <th class="Report-headerValue">Amount</th>
        <th class="Report-headerValue">Details</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td class="Report-value"> <%= order.user.first_name %> </td>
          <td class="Report-value"> <%= order.date %> </td>
          <td class="Report-value"> <%= order.delivered_at %> </td>
          <td class="Report-value"> <%= @totals[order.id] %> </td>
          <td class="Report-value"> <%= link_to "Show", order_items_path(order_id: order.id) %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <div class="Report-total">
    <p class="Report-totalValue"> Total Orders: <%= @count %> </p>
    <p class="Report-totalValue"> Total Amount: <%= @sum %> </p>
  </div>
</section>