config/routes.rb
Rails.application.routes.draw do
  get "/", to: "sessions#new"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
  get "/home", to: "home#index"
  get "/yourorder", to: "orders#your_orders"
  post "viewcart", to: "orders#view"
  get "/clerks", to: "clerks#index"
  get "/new_clerk", to: "clerks#new"
  get "/sales_report", to: "orders#report"
  resources :users
  resources :orders
  resources :order_items
  resources :menus
  resources :menu_items
  resources :carts
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <% if @current_user %>
      <div class="MainPage">
        <div class="SideNavBar">
          <h3 class="SideNavBar-header">MENU</h3>
          <p class="SideNavBar-item"><%= link_to "Home", home_path, class: "SideNavItem-link" %></p>
          <% if @current_user.role == "owner" %>
            <p class="SideNavBar-item"><%= link_to "View menus", menus_path, class: "SideNavItem-link" %> </p>
          <% end %>
          <p class="SideNavBar-item"><%= link_to "Browse", menu_items_path, class: "SideNavItem-link" %> </p>
          <p class="SideNavBar-item"><%= link_to "Order", new_order_path, class: "SideNavItem-link" %> </p>
          <% if not(@current_user.role == "customer") %>
            <p class="SideNavBar-item"><%= link_to "Pending Orders", orders_path, class: "SideNavItem-link" %> </p>
          <% end %>
          <p class="SideNavBar-item"><%= link_to "My orders", yourorder_path, class: "SideNavItem-link" %></p>
          <p class="SideNavBar-item"><%= link_to "My cart", carts_path, class: "SideNavItem-link" %></p>
          <% if @current_user.role == "owner" %>
            <p class="SideNavBar-item"><%= link_to "View sales report", sales_report_path, class: "SideNavItem-link" %></p>
            <p class="SideNavBar-item"><%= link_to "Manage clerks", clerks_path, class: "SideNavItem-link" %></p>
          <% end %>
          <p class="SideNavBar-item"><%= link_to "Sign out", destroy_session_path, method: "delete", class: "SideNavItem-link" %></p>
        </div>
        <div class="MainPage-header">
          <p class="MainPage-headerAppName">The Cafeteria Manager</p>
          <p class="MainPage-headerWelcomeMessage">
            Hi <%= @current_user.first_name + " " + @current_user.last_name %>!
          </p>
          <% if (@current_user.role == "owner") %>
            <p class="MainPage-ownerMessage">You have been registered as a cafeteria owner.</p>
          <% end %>
          <% if (@current_user.role == "clerk") %>
            <p class="MainPage-ownerMessage">You have been registered as a cafeteria clerk.</p>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if flash[:error] %>
      <p><%= flash[:error] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>